@echo off
echo Building Issues to ensure weaving...
dotnet build %~dp0TestAssemblies\Issues\Issues.csproj -c Debug
echo Building Mono Issue108 Test...
dotnet build %~dp0Rougamo.Mono.Tests\Rougamo.Mono.Tests.csproj -c Debug
echo Running Issue108 xUnit via Mono...
mono %USERPROFILE%\.nuget\packages\xunit.runner.console\2.4.2\tools\net472\xunit.console.exe %~dp0Rougamo.Mono.Tests\bin\Debug\net48\Rougamo.Mono.Tests.dll
pause
