@echo off
echo Building Issues to ensure weaving...
dotnet build %~dp0TestAssemblies\Issues\Issues.csproj -c Debug
echo Building Fody Tests...
dotnet build %~dp0Rougamo.Fody.Tests\Rougamo.Fody.Tests.csproj -c Debug -f net48
echo Running xUnit via Mono...
mono %USERPROFILE%\.nuget\packages\xunit.runner.console\2.4.2\tools\net472\xunit.console.exe %~dp0Rougamo.Fody.Tests\bin\Debug\net48\Rougamo.Fody.Tests.dll
pause
