//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rougamo.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rougamo.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Features property has been moved into AdviceAttribute..
        /// </summary>
        internal static string V4t5FeaturesRuleDescription {
            get {
                return ResourceManager.GetString("V4t5FeaturesRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Features property, which has been removed from IMo since version 5.0. Use AdviceAttribute instead..
        /// </summary>
        internal static string V4t5FeaturesRuleMessage {
            get {
                return ResourceManager.GetString("V4t5FeaturesRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Features property has been removed from IMo..
        /// </summary>
        internal static string V4t5FeaturesRuleTitle {
            get {
                return ResourceManager.GetString("V4t5FeaturesRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Flags property, which has been removed from IMo since version 5.0. Use IFlexibleModifierPointcut instead..
        /// </summary>
        internal static string V4t5FlagsFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("V4t5FlagsFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flags property has been moved into PointcutAttribute and IFlexibleModifierPointcut..
        /// </summary>
        internal static string V4t5FlagsRuleDescription {
            get {
                return ResourceManager.GetString("V4t5FlagsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Flags property, which has been removed from IMo since version 5.0. Use PointcutAttribute instead..
        /// </summary>
        internal static string V4t5FlagsRuleMessage {
            get {
                return ResourceManager.GetString("V4t5FlagsRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flags property has been removed from IMo..
        /// </summary>
        internal static string V4t5FlagsRuleTitle {
            get {
                return ResourceManager.GetString("V4t5FlagsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ForceSync property has been moved into OptimizationAttribute..
        /// </summary>
        internal static string V4t5ForceSyncRuleDescription {
            get {
                return ResourceManager.GetString("V4t5ForceSyncRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the ForceSync property, which has been removed from IMo since version 5.0. Use OptimizationAttribute instead..
        /// </summary>
        internal static string V4t5ForceSyncRuleMessage {
            get {
                return ResourceManager.GetString("V4t5ForceSyncRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ForceSync property has been removed from IMo..
        /// </summary>
        internal static string V4t5ForceSyncRuleTitle {
            get {
                return ResourceManager.GetString("V4t5ForceSyncRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MethodContextOmits property has been moved into OptimizationAttribute..
        /// </summary>
        internal static string V4t5OmitsRuleDescription {
            get {
                return ResourceManager.GetString("V4t5OmitsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the MethodContextOmits property, which has been removed from IMo since version 5.0. Use OptimizationAttribute instead..
        /// </summary>
        internal static string V4t5OmitsRuleMessage {
            get {
                return ResourceManager.GetString("V4t5OmitsRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MethodContextOmits property has been removed from IMo..
        /// </summary>
        internal static string V4t5OmitsRuleTitle {
            get {
                return ResourceManager.GetString("V4t5OmitsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Order property, which has been removed from IMo since version 5.0. Use IFlexibleOrderable instead..
        /// </summary>
        internal static string V4t5OrderFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("V4t5OrderFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order property has been moved into IFlexibleOrderable..
        /// </summary>
        internal static string V4t5OrderRuleDescription {
            get {
                return ResourceManager.GetString("V4t5OrderRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order property has been removed from IMo..
        /// </summary>
        internal static string V4t5OrderRuleTitle {
            get {
                return ResourceManager.GetString("V4t5OrderRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Pattern property, which has been removed from IMo since version 5.0. Use IFlexiblePatternPointcut instead..
        /// </summary>
        internal static string V4t5PatternFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("V4t5PatternFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern property has been moved into PointcutAttribute and IFlexiblePatternPointcut..
        /// </summary>
        internal static string V4t5PatternRuleDescription {
            get {
                return ResourceManager.GetString("V4t5PatternRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Pattern property, which has been removed from IMo since version 5.0. Use PointcutAttribute instead..
        /// </summary>
        internal static string V4t5PatternRuleMessage {
            get {
                return ResourceManager.GetString("V4t5PatternRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern property has been removed from IMo..
        /// </summary>
        internal static string V4t5PatternRuleTitle {
            get {
                return ResourceManager.GetString("V4t5PatternRuleTitle", resourceCulture);
            }
        }
    }
}
