//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rougamo.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rougamo.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Features property has been moved into AdviceAttribute..
        /// </summary>
        internal static string FeaturesRuleDescription {
            get {
                return ResourceManager.GetString("FeaturesRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Features property, which has been removed from IMo since version 5.0. Use AdviceAttribute instead..
        /// </summary>
        internal static string FeaturesRuleMessage {
            get {
                return ResourceManager.GetString("FeaturesRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Features property has been removed from IMo..
        /// </summary>
        internal static string FeaturesRuleTitle {
            get {
                return ResourceManager.GetString("FeaturesRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Flags property, which has been removed from IMo since version 5.0. Use IFlexibleModifierPointcut instead..
        /// </summary>
        internal static string FlagsFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("FlagsFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flags property has been moved into PointcutAttribute and IFlexibleModifierPointcut..
        /// </summary>
        internal static string FlagsRuleDescription {
            get {
                return ResourceManager.GetString("FlagsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Flags property, which has been removed from IMo since version 5.0. Use PointcutAttribute instead..
        /// </summary>
        internal static string FlagsRuleMessage {
            get {
                return ResourceManager.GetString("FlagsRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flags property has been removed from IMo..
        /// </summary>
        internal static string FlagsRuleTitle {
            get {
                return ResourceManager.GetString("FlagsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ForceSync property has been moved into OptimizationAttribute..
        /// </summary>
        internal static string ForceSyncRuleDescription {
            get {
                return ResourceManager.GetString("ForceSyncRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the ForceSync property, which has been removed from IMo since version 5.0. Use OptimizationAttribute instead..
        /// </summary>
        internal static string ForceSyncRuleMessage {
            get {
                return ResourceManager.GetString("ForceSyncRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ForceSync property has been removed from IMo..
        /// </summary>
        internal static string ForceSyncRuleTitle {
            get {
                return ResourceManager.GetString("ForceSyncRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MethodContextOmits property has been moved into OptimizationAttribute..
        /// </summary>
        internal static string OmitsRuleDescription {
            get {
                return ResourceManager.GetString("OmitsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the MethodContextOmits property, which has been removed from IMo since version 5.0. Use OptimizationAttribute instead..
        /// </summary>
        internal static string OmitsRuleMessage {
            get {
                return ResourceManager.GetString("OmitsRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MethodContextOmits property has been removed from IMo..
        /// </summary>
        internal static string OmitsRuleTitle {
            get {
                return ResourceManager.GetString("OmitsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Order property, which has been removed from IMo since version 5.0. Use IFlexibleOrderable instead..
        /// </summary>
        internal static string OrderFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("OrderFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order property has been moved into IFlexibleOrderable..
        /// </summary>
        internal static string OrderRuleDescription {
            get {
                return ResourceManager.GetString("OrderRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order property has been removed from IMo..
        /// </summary>
        internal static string OrderRuleTitle {
            get {
                return ResourceManager.GetString("OrderRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Pattern property, which has been removed from IMo since version 5.0. Use IFlexiblePatternPointcut instead..
        /// </summary>
        internal static string PatternFlexibleRuleMessage {
            get {
                return ResourceManager.GetString("PatternFlexibleRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern property has been moved into PointcutAttribute and IFlexiblePatternPointcut..
        /// </summary>
        internal static string PatternRuleDescription {
            get {
                return ResourceManager.GetString("PatternRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains the Pattern property, which has been removed from IMo since version 5.0. Use PointcutAttribute instead..
        /// </summary>
        internal static string PatternRuleMessage {
            get {
                return ResourceManager.GetString("PatternRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pattern property has been removed from IMo..
        /// </summary>
        internal static string PatternRuleTitle {
            get {
                return ResourceManager.GetString("PatternRuleTitle", resourceCulture);
            }
        }
    }
}
