#if NET48
using Xunit;

// <auto-generated>
// Generated by Mono48/Generate-Mono48Mirror.ps1
// </auto-generated>

namespace Rougamo.Fody.Tests.Mono48
{
    [Collection("Mono48")]
    public class MonoTests
    {
        [Fact] public void MonoStackTraceTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.MonoTests.MonoStackTraceTest");
    }

    [Collection("Mono48")]
    public class BasicTest
    {
        [Fact] public void MethodPropertyTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.MethodPropertyTest");
        [Fact] public void ModifyReturnValueTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.ModifyReturnValueTest");
        [Fact] public void AsyncModifyReturnValueTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.AsyncModifyReturnValueTest");
        [Fact] public void ModifyIteratorReturnValueTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.ModifyIteratorReturnValueTest");
        [Fact] public void SyncTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.SyncTest");
        [Fact] public void AsyncTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.AsyncTest");
        [Fact] public void ArgumentRewriteTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.ArgumentRewriteTest");
        [Fact] public void RetryTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.RetryTest");
        [Fact] public void OrderTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.OrderTest");
        [Fact] public void FreshArgsTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.FreshArgsTest");
        [Fact] public void RougamoTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.RougamoTest");
        [Fact] public void OmitTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.OmitTest");
        [Fact] public void IndirectDependencyTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.IndirectDependencyTest");
        [Fact] public void CtorTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.CtorTest");
        [Fact] public void LifetimeTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.BasicTest.LifetimeTest");
    }

    [Collection("Mono48")]
    public class IssueTest
    {
        [Fact] public void Issue8Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue8Test");
        [Fact] public void Issue9Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue9Test");
        [Fact] public void Issue16Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue16Test");
        [Fact] public void Issue20Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue20Test");
        [Fact] public void Issue25Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue25Test");
        [Fact] public void Issue27Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue27Test");
        [Fact] public void Issue30Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue30Test");
        [Fact] public void Issue40Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue40Test");
        [Fact] public void Issue51Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue51Test");
        [Fact] public void Issue60Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue60Test");
        [Fact] public void Issue61Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue61Test");
        [Fact] public void Issue66Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue66Test");
        [Fact] public void Issue72Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue72Test");
        [Fact] public void Issue73Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue73Test");
        [Fact] public void Issue79Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue79Test");
        [Fact] public void Issue80Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue80Test");
        [Fact] public void Issue81Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue81Test");
        [Fact] public void Issue83Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue83Test");
        [Fact] public void Issue86Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue86Test");
        [Fact] public void Issue97Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue97Test");
        [Fact] public void Issue106Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue106Test");
        [Fact] public void Issue107Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.IssueTest.Issue107Test");
    }

    [Collection("Mono48")]
    public class ConfiguredMoTests
    {
        [Fact] public void Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.ConfiguredMoTests.Test");
    }

    [Collection("Mono48")]
    public class PatternTests
    {
        [Fact] public void MethodGlobalModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodGlobalModifierTest");
        [Fact] public void MethodIRougamoTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodIRougamoTest");
        [Fact] public void MethodFuzzyNameTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodFuzzyNameTest");
        [Fact] public void ExecutionChildFullyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionChildFullyMatchTest");
        [Fact] public void ExecutionChildNameMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionChildNameMatchTest");
        [Fact] public void GetterReturnsDictionaryGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.GetterReturnsDictionaryGenericTest");
        [Fact] public void SetterReturnsChildOfIDictionaryTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.SetterReturnsChildOfIDictionaryTest");
        [Fact] public void PropertyReturnsChildOfDicOrListTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.PropertyReturnsChildOfDicOrListTest");
        [Fact] public void MethodAnyMethodGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodAnyMethodGenericTest");
        [Fact] public void ExecutionSingleMethodGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionSingleMethodGenericTest");
        [Fact] public void ExecutionDoubleMethodGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionDoubleMethodGenericTest");
        [Fact] public void ExecutionSingleTypeGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionSingleTypeGenericTest");
        [Fact] public void ExecutionDoubleTypeGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionDoubleTypeGenericTest");
        [Fact] public void ExecutionAnyTypeGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionAnyTypeGenericTest");
        [Fact] public void ExecutionAnyTypeGenericNoneMethodGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionAnyTypeGenericNoneMethodGenericTest");
        [Fact] public void ExecutionNoneTypeGenericAnyMethodGenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionNoneTypeGenericAnyMethodGenericTest");
        [Fact] public void MethodNestedTypeTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodNestedTypeTest");
        [Fact] public void MethodArrayTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodArrayTest");
        [Fact] public void ParameterTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ParameterTest");
        [Fact] public void GenericParameterMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.GenericParameterMatchTest");
        [Fact] public void ExecutionTupleSyntaxTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionTupleSyntaxTest");
        [Fact] public void MethodAsyncSyntaxTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodAsyncSyntaxTest");
        [Fact] public void ExecutionNullableSyntaxTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ExecutionNullableSyntaxTest");
        [Fact] public void MethodNotSyntaxTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.MethodNotSyntaxTest");
        [Fact] public void RegexTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.RegexTest");
        [Fact] public void InlineTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.InlineTest");
        [Fact] public void ApllyToMethodDirectlyTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.ApllyToMethodDirectlyTest");
        [Fact] public void IntegrativeTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.IntegrativeTest");
        [Fact] public void AttributeTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.PatternTests.AttributeTest");
    }

}

namespace Rougamo.Fody.Tests.Mono48.Signatures
{
    [Collection("Mono48")]
    public class SignatureBasicTests
    {
        [Fact] public void PublicClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicClassModifierTest");
        [Fact] public void InternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalClassModifierTest");
        [Fact] public void DefaultClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultClassModifierTest");
        [Fact] public void PublicNestedPublicClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedPublicClassModifierTest");
        [Fact] public void PublicNestedProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedProtectedClassModifierTest");
        [Fact] public void PublicNestedPrivateClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedPrivateClassModifierTest");
        [Fact] public void PublicNestedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedInternalClassModifierTest");
        [Fact] public void PublicNestedProtectedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedProtectedInternalClassModifierTest");
        [Fact] public void PublicNestedPrivateProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.PublicNestedPrivateProtectedClassModifierTest");
        [Fact] public void InternalNestedPublicClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedPublicClassModifierTest");
        [Fact] public void InternalNestedProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedProtectedClassModifierTest");
        [Fact] public void InternalNestedPrivateClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedPrivateClassModifierTest");
        [Fact] public void InternalNestedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedInternalClassModifierTest");
        [Fact] public void InternalNestedProtectedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedProtectedInternalClassModifierTest");
        [Fact] public void InternalNestedPrivateProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.InternalNestedPrivateProtectedClassModifierTest");
        [Fact] public void DefaultNestedPublicClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedPublicClassModifierTest");
        [Fact] public void DefaultNestedProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedProtectedClassModifierTest");
        [Fact] public void DefaultNestedPrivateClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedPrivateClassModifierTest");
        [Fact] public void DefaultNestedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedInternalClassModifierTest");
        [Fact] public void DefaultNestedProtectedInternalClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedProtectedInternalClassModifierTest");
        [Fact] public void DefaultNestedPrivateProtectedClassModifierTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.DefaultNestedPrivateProtectedClassModifierTest");
        [Fact] public void GenericTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SignatureBasicTests.GenericTest");
    }

    [Collection("Mono48")]
    public class WildcardMatchTests
    {
        [Fact] public void NonWildcardTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.WildcardMatchTests.NonWildcardTest");
        [Fact] public void StarTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.WildcardMatchTests.StarTest");
        [Fact] public void EillipsisTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.WildcardMatchTests.EillipsisTest");
        [Fact] public void StarEllipsisTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.WildcardMatchTests.StarEllipsisTest");
    }

    [Collection("Mono48")]
    public class PropertyMatchTests
    {
        [Fact] public void AnyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PropertyMatchTests.AnyMatchTest");
        [Fact] public void MidifierMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PropertyMatchTests.MidifierMatchTest");
        [Fact] public void WildNameMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PropertyMatchTests.WildNameMatchTest");
        [Fact] public void AssignableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PropertyMatchTests.AssignableMatchTest");
    }

    [Collection("Mono48")]
    public class GetterMatchTests
    {
        [Fact] public void AnyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.GetterMatchTests.AnyMatchTest");
        [Fact] public void MidifierMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.GetterMatchTests.MidifierMatchTest");
        [Fact] public void WildNameMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.GetterMatchTests.WildNameMatchTest");
        [Fact] public void AssignableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.GetterMatchTests.AssignableMatchTest");
    }

    [Collection("Mono48")]
    public class SetterMatchTests
    {
        [Fact] public void AnyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SetterMatchTests.AnyMatchTest");
        [Fact] public void MidifierMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SetterMatchTests.MidifierMatchTest");
        [Fact] public void WildNameMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SetterMatchTests.WildNameMatchTest");
        [Fact] public void AssignableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.SetterMatchTests.AssignableMatchTest");
    }

    [Collection("Mono48")]
    public class PatternParseTests
    {
        [Fact] public void UnionTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PatternParseTests.UnionTest");
        [Fact] public void RegexPatternTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PatternParseTests.RegexPatternTest");
        [Fact] public void RegexWithGroupTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PatternParseTests.RegexWithGroupTest");
        [Fact] public void ModifierPatternTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PatternParseTests.ModifierPatternTest");
        [Fact] public void Test() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.PatternParseTests.Test");
    }

    [Collection("Mono48")]
    public class ExecutionMatchTests
    {
        [Fact] public void AnyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.AnyMatchTest");
        [Fact] public void ModifierMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.ModifierMatchTest");
        [Fact] public void MethodGenericMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.MethodGenericMatchTest");
        [Fact] public void NestedTypeMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.NestedTypeMatchTest");
        [Fact] public void AssignableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.AssignableMatchTest");
        [Fact] public void NotMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.NotMatchTest");
        [Fact] public void NotDeclaringMethodTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.NotDeclaringMethodTest");
        [Fact] public void OrMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.OrMatchTest");
        [Fact] public void TupleMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.TupleMatchTest");
        [Fact] public void NullableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.NullableMatchTest");
        [Fact] public void AsyncMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.ExecutionMatchTests.AsyncMatchTest");
    }

    [Collection("Mono48")]
    public class MethodMatchTests
    {
        [Fact] public void AnyMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.AnyMatchTest");
        [Fact] public void ModifierMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.ModifierMatchTest");
        [Fact] public void MethodGenericMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.MethodGenericMatchTest");
        [Fact] public void NestedTypeMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.NestedTypeMatchTest");
        [Fact] public void AssignableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.AssignableMatchTest");
        [Fact] public void NotMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.NotMatchTest");
        [Fact] public void NotDeclaringMethodTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.NotDeclaringMethodTest");
        [Fact] public void OrMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.OrMatchTest");
        [Fact] public void TupleMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.TupleMatchTest");
        [Fact] public void NullableMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.NullableMatchTest");
        [Fact] public void AsyncMatchTest() => MonoRunnerBridge.RunMonoFact("Rougamo.Fody.Tests.Signatures.MethodMatchTests.AsyncMatchTest");
    }

}

#endif
